### ISSUE TITLE
Picard running out of disk space

### ISSUE THREAD

**Issue by MarWoes** [MarWoes/wg-blimp#8]
When `/tmp` has size constrains, Picard may fail. Picard's `TMP_DIR` should be configurable through config files.

**Comment by MarWoes** [comment]
Fixed by fc9795c6062b60f7558a0bdeb2c2678b0e26d561

**Comment by MarWoes** [comment]
Included in release v0.9.6

**Comment by harish0201** [comment]
Hi,

From grepping on the repo, I found that Picard was being used to Mark Dups.

Would you be comfortable in adding samblaster instead of Picard as it involves something similar to this:

`````
bwameth.py --reference ref.fa t_R1.fastq.gz t_R2.fastq.gz -t 12 | samblaster | samtools view -Shbo output.bam
`````

Which might be fairly trivial as it marks duplicates on the fly with Picard's approach (from what I've read about it)?

**Comment by MarWoes** [comment]
Thanks for your comment! We were using Picard and samtools for stability reasons (back in the day sambamba had some issues with our data). I think it might be worth revisiting both tools to maybe accelerate everything, I'll have a look!
